// <auto-generated />
using System;
using Din.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Din.Data.Migrations.Migrations
{
    [DbContext(typeof(DinContext))]
    [Migration("20190421152558_table-names")]
    partial class tablenames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Din.Domain.Models.Entity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Hash");

                    b.Property<Guid?>("ImageId");

                    b.Property<int>("Role");

                    b.Property<string>("Username")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Din.Domain.Models.Entity.AccountImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Data");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("AccountImage");
                });

            modelBuilder.Entity("Din.Domain.Models.Entity.AddedContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountRef");

                    b.Property<DateTime>("DateAdded");

                    b.Property<int>("Eta");

                    b.Property<int>("ForeignId");

                    b.Property<double>("Percentage");

                    b.Property<int>("Status");

                    b.Property<int>("SystemId");

                    b.Property<string>("Title");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("AccountRef");

                    b.ToTable("AddedContent");
                });

            modelBuilder.Entity("Din.Domain.Models.Entity.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Browser");

                    b.Property<DateTime>("DateAndTime");

                    b.Property<string>("Device");

                    b.Property<Guid?>("LocationId");

                    b.Property<string>("Os");

                    b.Property<string>("PublicIp");

                    b.Property<int>("Status");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("LoginAttempts");
                });

            modelBuilder.Entity("Din.Domain.Models.Entity.LoginLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("ContinentCode");

                    b.Property<string>("ContinentName");

                    b.Property<string>("CountryCode");

                    b.Property<string>("CountryName");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<string>("RegionCode");

                    b.Property<string>("RegionName");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("LoginLocation");
                });

            modelBuilder.Entity("Din.Domain.Models.Entity.Account", b =>
                {
                    b.HasOne("Din.Domain.Models.Entity.AccountImage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");
                });

            modelBuilder.Entity("Din.Domain.Models.Entity.AddedContent", b =>
                {
                    b.HasOne("Din.Domain.Models.Entity.Account", "Account")
                        .WithMany("AddedContent")
                        .HasForeignKey("AccountRef")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Din.Domain.Models.Entity.LoginAttempt", b =>
                {
                    b.HasOne("Din.Domain.Models.Entity.LoginLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");
                });
#pragma warning restore 612, 618
        }
    }
}
