// <auto-generated />
using System;
using Din.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Din.Migrations
{
    [DbContext(typeof(DinContext))]
    [Migration("20181208113023_generate-guid")]
    partial class generateguid
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Din.Data.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Hash");

                    b.Property<int>("Role");

                    b.Property<Guid>("UserRef");

                    b.Property<string>("Username")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("UserRef")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Din.Data.Entities.AccountImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountRef");

                    b.Property<byte[]>("Data");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AccountRef")
                        .IsUnique();

                    b.ToTable("AccountImage");
                });

            modelBuilder.Entity("Din.Data.Entities.AddedContentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountRef");

                    b.Property<DateTime>("DateAdded");

                    b.Property<int>("Eta");

                    b.Property<int>("ForeignId");

                    b.Property<double>("Percentage");

                    b.Property<int>("Status");

                    b.Property<int>("SystemId");

                    b.Property<string>("Title");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("AccountRef");

                    b.ToTable("AddedContent");
                });

            modelBuilder.Entity("Din.Data.Entities.LoginAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Browser");

                    b.Property<DateTime>("DateAndTime");

                    b.Property<string>("Device");

                    b.Property<Guid?>("LocationId");

                    b.Property<string>("Os");

                    b.Property<string>("PublicIp");

                    b.Property<int>("Status");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("LoginAttempt");
                });

            modelBuilder.Entity("Din.Data.Entities.LoginLocationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("ContinentCode");

                    b.Property<string>("ContinentName");

                    b.Property<string>("CountryCode");

                    b.Property<string>("CountryName");

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<string>("RegionCode");

                    b.Property<string>("RegionName");

                    b.Property<string>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("LoginLocation");
                });

            modelBuilder.Entity("Din.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Din.Data.Entities.AccountEntity", b =>
                {
                    b.HasOne("Din.Data.Entities.UserEntity", "User")
                        .WithOne("Account")
                        .HasForeignKey("Din.Data.Entities.AccountEntity", "UserRef")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Din.Data.Entities.AccountImageEntity", b =>
                {
                    b.HasOne("Din.Data.Entities.AccountEntity", "Account")
                        .WithOne("Image")
                        .HasForeignKey("Din.Data.Entities.AccountImageEntity", "AccountRef")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Din.Data.Entities.AddedContentEntity", b =>
                {
                    b.HasOne("Din.Data.Entities.AccountEntity", "Account")
                        .WithMany("AddedContent")
                        .HasForeignKey("AccountRef")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Din.Data.Entities.LoginAttemptEntity", b =>
                {
                    b.HasOne("Din.Data.Entities.LoginLocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");
                });
#pragma warning restore 612, 618
        }
    }
}
